# Notebook 01 — Préparation des données
## Projet : Aide à la commercialisation foncière — WISDOM International

Objectif de ce notebook : charger le fichier de suivi des lots,
comprendre sa structure, puis le nettoyer pour produire une base
de données propre et exploitable.

In [1]:
import pandas as pd

# Chemin vers ton fichier brut
chemin = "../01_donnees_brutes/suivi_lots_2021.xlsx"

# On ouvre le classeur sans lire les données, juste pour l'inspecter
classeur = pd.ExcelFile(chemin)

print("Nombre de feuilles :", len(classeur.sheet_names))
print("\nListe des feuilles :")
for nom in classeur.sheet_names:
    print(" -", nom)

Nombre de feuilles : 37

Liste des feuilles :
 - 5880
 - Feuil1
 - Feuil2
 - Feuil3
 - Feuil5
 - Feuil6
 - 5881
 - 3638
 - 5262 KADJO
 - KOMGUEM KAINNENG NADEGE
 -  KOMGUEM KAINNENG NADEGE 2
 - RECAP DES DISPONIBILIT
 - Recap des RECAP26
 - DISPONIBILITES
 - Recap 25
 - Dla(Mme PAGUY Epse DJOUMESSI)
 - 5792 YANGA
 - 6428 LISSOM
 - sup TOTAL DE LIKOUND
 - 3638(2)
 - 6428(4 et 9)
 - 5216 nvo
 - 3905 nvo
 - 5608
 - 5880(02)
 - 5176 nvo
 - 4192
 - 5066
 - 6037
 - 5608SM
 - 3989
 - 3368
 - TOTAL
 - Situation
 - NGOI EMMANUEL( 29180)
 - ..
 - Feuille37

In [1]:
import pandas as pd

# Chemin vers ton fichier brut
chemin = "../01_donnees_brutes/suivi_lots_2021.xlsx"

# On ouvre le classeur sans lire les données, juste pour l'inspecter
classeur = pd.ExcelFile(chemin)

print("Nombre de feuilles :", len(classeur.sheet_names))
print("\nListe des feuilles :")
for nom in classeur.sheet_names:
    print(" -", nom)

Nombre de feuilles : 37

Liste des feuilles :
 - 5880
 - Feuil1
 - Feuil2
 - Feuil3
 - Feuil5
 - Feuil6
 - 5881
 - 3638
 - 5262 KADJO
 - KOMGUEM KAINNENG NADEGE
 -  KOMGUEM KAINNENG NADEGE 2
 - RECAP DES DISPONIBILIT
 - Recap des RECAP26
 - DISPONIBILITES
 - Recap 25
 - Dla(Mme PAGUY Epse DJOUMESSI)
 - 5792 YANGA
 - 6428 LISSOM
 - sup TOTAL DE LIKOUND
 - 3638(2)
 - 6428(4 et 9)
 - 5216 nvo
 - 3905 nvo
 - 5608
 - 5880(02)
 - 5176 nvo
 - 4192
 - 5066
 - 6037
 - 5608SM
 - 3989
 - 3368
 - TOTAL
 - Situation
 - NGOI EMMANUEL( 29180)
 - ..
 - Feuille37

In [2]:
# On lit UNE feuille pour examiner sa structure interne.
# header=None : on NE suppose PAS que la 1re ligne est un en-tête,
# car ces feuilles ont souvent des titres avant le vrai tableau.
feuille = pd.read_excel(chemin, sheet_name="5608", header=None)

print("Dimensions (lignes, colonnes) :", feuille.shape)

# On affiche les 15 premières lignes pour voir comment c'est organisé
feuille.head(15)

Dimensions (lignes, colonnes) : (188, 16)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,TF 5608/SM LIKOUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BLOC,LOT,SUPERFICIE,OCCUPEE,RESTANTE,NOMS ET PRENOMS DE CLIENTS,NaN,NaN,OBSERVATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,1,537,537,0,MBOCK MAURICE,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,2,537,537,0,NGAMI CLADIN'S MICHAEL,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,3,500,500,0,NTONGYE YVONNE NOMBO,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,4,500,500,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,5,500,500,0,LEWOUE NGUENTCHUENG THIBAUT,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,6,500,500,0,NGUELLOT TENE,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,7,500,500,0,NOUE ISABELLE,NaN,NaN,DT,.,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,8,500,500,0,NTSAMA BERTRAND,NaN,NaN,ECHEANCE PAS ENCORE TERMINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,9,500,500,0,NOUE MARIE ANGE,NaN,NaN,ECHEANCE PAS ENCORE TERMINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,10,500,500,0,NSIANI MBOULIE BRUNETTE,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,11,250,250,0,TATCHIM,NaN,NaN,ECHEANCE PAS ENCORE TERMINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# header=3 : on dit à pandas que la ligne d'indice 3 contient les noms de colonnes
feuille = pd.read_excel(chemin, sheet_name="5608", header=3)

print("Colonnes détectées :")
print(list(feuille.columns))

feuille.head(12)

Colonnes détectées :
['BLOC', 'LOT', 'SUPERFICIE', 'OCCUPEE', 'RESTANTE', 'NOMS ET PRENOMS DE CLIENTS', 'Unnamed: 6', 'Unnamed: 7', 'OBSERVATIONS', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

,BLOC,LOT,SUPERFICIE,OCCUPEE,RESTANTE,NOMS ET PRENOMS DE CLIENTS,Unnamed: 6,Unnamed: 7,OBSERVATIONS,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,16,1,537,537,0,MBOCK MAURICE,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2,537,537,0,NGAMI CLADIN'S MICHAEL,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,3,500,500,0,NTONGYE YVONNE NOMBO,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,4,500,500,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,5,500,500,0,LEWOUE NGUENTCHUENG THIBAUT,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,6,500,500,0,NGUELLOT TENE,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,7,500,500,0,NOUE ISABELLE,NaN,NaN,DT,.,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,8,500,500,0,NTSAMA BERTRAND,NaN,NaN,ECHEANCE PAS ENCORE TERMINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,9,500,500,0,NOUE MARIE ANGE,NaN,NaN,ECHEANCE PAS ENCORE TERMINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,10,500,500,0,NSIANI MBOULIE BRUNETTE,NaN,NaN,DT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,11,250,250,0,TATCHIM,NaN,NaN,ECHEANCE PAS ENCORE TERMINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,250,250,0,ABOUAG S/c EBELLE CATHY,NaN,NaN,DT ENCOURS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Dictionnaire : ancien nom  ->  nouveau nom (plus simple)
colonnes_utiles = {
    "BLOC": "bloc",
    "LOT": "lot",
    "SUPERFICIE": "superficie",
    "OCCUPEE": "occupee",
    "RESTANTE": "restante",
    "NOMS ET PRENOMS DE CLIENTS": "client",
    "OBSERVATIONS": "observation",
}

# On garde uniquement ces colonnes, puis on les renomme
feuille = feuille[list(colonnes_utiles.keys())].rename(columns=colonnes_utiles)

feuille.head(12)

,bloc,lot,superficie,occupee,restante,client,observation
0,16,1,537,537,0,MBOCK MAURICE,DT
1,NaN,2,537,537,0,NGAMI CLADIN'S MICHAEL,DT
2,NaN,3,500,500,0,NTONGYE YVONNE NOMBO,DT
3,NaN,4,500,500,0,NaN,NaN
4,NaN,5,500,500,0,LEWOUE NGUENTCHUENG THIBAUT,DT
5,NaN,6,500,500,0,NGUELLOT TENE,DT
6,NaN,7,500,500,0,NOUE ISABELLE,DT
7,NaN,8,500,500,0,NTSAMA BERTRAND,ECHEANCE PAS ENCORE TERMINE
8,NaN,9,500,500,0,NOUE MARIE ANGE,ECHEANCE PAS ENCORE TERMINE
9,NaN,10,500,500,0,NSIANI MBOULIE BRUNETTE,DT
10,NaN,11,250,250,0,TATCHIM,ECHEANCE PAS ENCORE TERMINE
11,NaN,NaN,250,250,0,ABOUAG S/c EBELLE CATHY,DT ENCOURS

In [5]:
# .ffill() = forward fill : chaque case vide de "bloc" est remplie
# avec la dernière valeur de bloc rencontrée au-dessus.
feuille["bloc"] = feuille["bloc"].ffill()

feuille.head(12)

,bloc,lot,superficie,occupee,restante,client,observation
0,16,1,537,537,0,MBOCK MAURICE,DT
1,16,2,537,537,0,NGAMI CLADIN'S MICHAEL,DT
2,16,3,500,500,0,NTONGYE YVONNE NOMBO,DT
3,16,4,500,500,0,NaN,NaN
4,16,5,500,500,0,LEWOUE NGUENTCHUENG THIBAUT,DT
5,16,6,500,500,0,NGUELLOT TENE,DT
6,16,7,500,500,0,NOUE ISABELLE,DT
7,16,8,500,500,0,NTSAMA BERTRAND,ECHEANCE PAS ENCORE TERMINE
8,16,9,500,500,0,NOUE MARIE ANGE,ECHEANCE PAS ENCORE TERMINE
9,16,10,500,500,0,NSIANI MBOULIE BRUNETTE,DT
10,16,11,250,250,0,TATCHIM,ECHEANCE PAS ENCORE TERMINE
11,16,NaN,250,250,0,ABOUAG S/c EBELLE CATHY,DT ENCOURS

In [6]:
# 1) Combien de valeurs manquantes (NaN) dans chaque colonne ?
print("Valeurs manquantes par colonne :")
print(feuille.isna().sum())

print("\nNombre total de lignes :", len(feuille))

# 2) Les dernières lignes : on y trouve souvent des totaux ou des lignes vides
feuille.tail(15)

Valeurs manquantes par colonne :
bloc            0
lot            78
superficie     34
occupee        36
restante       32
client         56
observation    88
dtype: int64

Nombre total de lignes : 184

,bloc,lot,superficie,occupee,restante,client,observation
169,18,3,701,701,0,BAYIHA BAYIHA Isidore,NaN
170,18,4,701,701,0,BAYIHA BAYIHA Isidore,NaN
171,TOTAL BLOC 19,NaN,2670,2670,1824,NaN,NaN
172,TOTAL BLOC 19,NaN,NaN,NaN,NaN,NaN,NaN
173,TOTAL BLOC 19,NaN,NaN,NaN,NaN,NaN,NaN
174,TOTAL BLOC 19,NaN,NaN,NaN,NaN,NaN,NaN
175,BLOC,LOTS,SUPERFICIE,OCCUPEE,RESTANTE,NOMS et PRENOMS CLIENTS,OBSERVATIONS
176,30,1,1060,0,1060,NaN,NaN
177,30,2,978,0,978,NaN,NaN
178,30,3,488,NaN,488,NaN,NaN
179,30,NaN,12,12,0,SAHAL MAUREL,NaN
180,30,4,500,0,500,NaN,NaN
181,30,5,488,488,0,SAHAL MAUREL,NaN
182,30,6,488,0,488,NaN,NaN
183,TOTAL BLOC 19,NaN,4014,12,3514,NaN,NaN

In [7]:
# On convertit lot et superficie en nombres.
# errors="coerce" : ce qui n'est PAS un nombre (texte "LOTS", "TOTAL BLOC 19"...)
# devient automatiquement NaN (vide).
feuille["lot"] = pd.to_numeric(feuille["lot"], errors="coerce")
feuille["superficie"] = pd.to_numeric(feuille["superficie"], errors="coerce")

# On garde seulement les lignes où lot ET superficie sont des nombres valides
avant = len(feuille)
feuille = feuille.dropna(subset=["lot", "superficie"])

print(f"Avant : {avant} lignes")
print(f"Après : {len(feuille)} lignes")
print(f"Supprimées (totaux, en-têtes, vides) : {avant - len(feuille)}")

feuille.tail(15)

Avant : 184 lignes
Après : 96 lignes
Supprimées (totaux, en-têtes, vides) : 88

    bloc  lot  superficie occupee restante                 client observation
149   19  2.0       543.0     NaN      543                    NaN         NaN
151   19  3.0       500.0       0      500                    NaN         NaN
152   19  4.0       188.0     188        0     DIFFO POKEM FRANCK         NaN
155   19  5.0        87.0       0       87                    NaN         NaN
158   19  6.0       488.0     488        0  KENFACK ZANKIA WINNIE         NaN
167   18  1.0       801.0     801        0  BAYIHA BAYIHA Isidore         NaN
168   18  2.0       467.0     467        0  BAYIHA BAYIHA Isidore         NaN
169   18  3.0       701.0     701        0  BAYIHA BAYIHA Isidore         NaN
170   18  4.0       701.0     701        0  BAYIHA BAYIHA Isidore         NaN
176   30  1.0      1060.0       0     1060                    NaN         NaN
177   30  2.0       978.0       0      978                    NaN         NaN
178   30  3.0       488.0     NaN      488                    NaN         NaN
180   30  4.0       500.0       0      500                    NaN         NaN
181   30  5.0       488.0     488        0           SAHAL MAUREL         NaN
182   30  6.0       488.0       0      488                    NaN         NaN

In [8]:
# On convertit le bloc en nombre entier.
# Int64 (avec majuscule) est un type entier qui tolère les valeurs vides.
feuille["bloc"] = pd.to_numeric(feuille["bloc"], errors="coerce").astype("Int64")

# Vérification : combien de parcelles par bloc dans cette feuille ?
print("Nombre de parcelles par bloc :")
print(feuille["bloc"].value_counts().sort_index())

Nombre de parcelles par bloc :
bloc
11    16
12     6
16    14
18     4
19     6
20     8
21     8
22    14
29    14
30     6
Name: count, dtype: Int64

In [9]:
# On s'assure que "restante" est bien numérique
feuille["restante"] = pd.to_numeric(feuille["restante"], errors="coerce")

# Règle métier :
#   restante = 0   -> parcelle payée      -> "Vendu"
#   restante > 0   -> reste à commercialiser -> "Disponible"
feuille["statut"] = feuille["restante"].apply(
    lambda r: "Vendu" if r == 0 else "Disponible"
)

# Vérification : la répartition vendus / disponibles
print(feuille["statut"].value_counts())

# Aperçu avec les colonnes clés
feuille[["bloc", "lot", "superficie", "restante", "client", "statut"]].head(12)

statut
Vendu         85
Disponible    11
Name: count, dtype: int64

,bloc,lot,superficie,restante,client,statut
0,16,1.0,537.0,0,MBOCK MAURICE,Vendu
1,16,2.0,537.0,0,NGAMI CLADIN'S MICHAEL,Vendu
2,16,3.0,500.0,0,NTONGYE YVONNE NOMBO,Vendu
3,16,4.0,500.0,0,NaN,Vendu
4,16,5.0,500.0,0,LEWOUE NGUENTCHUENG THIBAUT,Vendu
5,16,6.0,500.0,0,NGUELLOT TENE,Vendu
6,16,7.0,500.0,0,NOUE ISABELLE,Vendu
7,16,8.0,500.0,0,NTSAMA BERTRAND,Vendu
8,16,9.0,500.0,0,NOUE MARIE ANGE,Vendu
9,16,10.0,500.0,0,NSIANI MBOULIE BRUNETTE,Vendu
10,16,11.0,250.0,0,TATCHIM,Vendu
12,16,12.0,471.0,0,NGOUNOU KEWALA MACDOWELL S/c WONIG,Vendu

In [10]:
# 1) D'où viennent ces parcelles ? On marque le titre foncier.
feuille["TF"] = "5608"

# 2) Version numérique de la cible : 1 si vendu, 0 sinon
feuille["vendu"] = (feuille["statut"] == "Vendu").astype(int)

# 3) On garde et ordonne les colonnes finales
colonnes_finales = ["TF", "bloc", "lot", "superficie", "restante", "client", "statut", "vendu"]
feuille_5608 = feuille[colonnes_finales].reset_index(drop=True)

print("Forme finale :", feuille_5608.shape)
feuille_5608.head()

Forme finale : (96, 8)

,TF,bloc,lot,superficie,restante,client,statut,vendu
0,5608,16,1.0,537.0,0,MBOCK MAURICE,Vendu,1
1,5608,16,2.0,537.0,0,NGAMI CLADIN'S MICHAEL,Vendu,1
2,5608,16,3.0,500.0,0,NTONGYE YVONNE NOMBO,Vendu,1
3,5608,16,4.0,500.0,0,NaN,Vendu,1
4,5608,16,5.0,500.0,0,LEWOUE NGUENTCHUENG THIBAUT,Vendu,1

In [11]:
def nettoyer_feuille(nom_feuille):
    # 1) Lecture brute pour repérer la ligne d'en-tête (celle qui contient BLOC et LOT)
    brut = pd.read_excel(chemin, sheet_name=nom_feuille, header=None)
    ligne_entete = None
    for i in range(min(15, len(brut))):
        ligne = brut.iloc[i].astype(str).str.upper()
        if ligne.str.contains("BLOC").any() and ligne.str.contains("LOT").any():
            ligne_entete = i
            break
    if ligne_entete is None:
        return None   # pas une feuille de parcelles -> on l'ignore

    # 2) Relecture avec le bon en-tête
    df = pd.read_excel(chemin, sheet_name=nom_feuille, header=ligne_entete)

    # 3) Renommer les colonnes utiles en cherchant des mots-clés
    renom = {}
    for col in df.columns:
        c = str(col).upper()
        if "BLOC" in c: renom[col] = "bloc"
        elif "LOT" in c: renom[col] = "lot"
        elif "SUPERFICIE" in c: renom[col] = "superficie"
        elif "RESTANTE" in c: renom[col] = "restante"
        elif "CLIENT" in c or "NOMS" in c: renom[col] = "client"
    df = df.rename(columns=renom)

    # 4) Vérifier qu'on a bien les colonnes essentielles
    if not all(c in df.columns for c in ["bloc", "lot", "superficie", "restante"]):
        return None

    # 5) Nettoyage (exactement nos étapes manuelles)
    df["bloc"] = df["bloc"].ffill()
    for c in ["bloc", "lot", "superficie", "restante"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df.dropna(subset=["bloc", "lot", "superficie"])

    # 6) Statut + cible + titre foncier
    df["statut"] = df["restante"].apply(lambda r: "Vendu" if r == 0 else "Disponible")
    df["vendu"] = (df["statut"] == "Vendu").astype(int)
    df["TF"] = nom_feuille
    if "client" not in df.columns:
        df["client"] = None

    # 7) Colonnes finales
    return df[["TF","bloc","lot","superficie","restante","client","statut","vendu"]].reset_index(drop=True)


# On teste la fonction sur la feuille qu'on connaît déjà : 5608
test = nettoyer_feuille("5608")
print("Forme obtenue :", test.shape)
test.head()

Forme obtenue : (96, 8)

,TF,bloc,lot,superficie,restante,client,statut,vendu
0,5608,16.0,1.0,537.0,0.0,MBOCK MAURICE,Vendu,1
1,5608,16.0,2.0,537.0,0.0,NGAMI CLADIN'S MICHAEL,Vendu,1
2,5608,16.0,3.0,500.0,0.0,NTONGYE YVONNE NOMBO,Vendu,1
3,5608,16.0,4.0,500.0,0.0,NaN,Vendu,1
4,5608,16.0,5.0,500.0,0.0,LEWOUE NGUENTCHUENG THIBAUT,Vendu,1

In [13]:
# Pourquoi le titre foncier 5880 est-il ignoré ? Regardons sa structure brute.
brut = pd.read_excel(chemin, sheet_name="5880", header=None)

print("Dimensions :", brut.shape)
brut.head(12)

Dimensions : (83, 9)

,0,1,2,3,4,5,6,7,8
0,T.F 5880/SM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BLOC,LOT,SUPERFICIE,OCCUPEE,RESTANT,OCCUPANT,NaN,NaN,NaN
3,4,9,500,500,0,KAMTE EMMA,NaN,NaN,NaN
4,NaN,10,500,500,0,TCHUIMBOU SIKAZI SERGES PATRICK,NaN,NaN,NaN
5,NaN,11,500,NaN,500,ONGUENE CLAUDE BERTRAND JUNIOR,NaN,NaN,NaN
6,NaN,12,500,500,0,TCHUIMBOU SIKAZI SERGES PATRICK,NaN,NaN,NaN
7,NaN,13,500,NaN,500,NYOM ANDRE RENE,NaN,NaN,NaN
8,NaN,14,500,NaN,500,NYOM ANDRE RENE,NaN,NaN,NaN
9,TOTAL BLOC 4,NaN,3000,1500,1500,NaN,NaN,NaN,NaN
10,BLOC,LOT,SUPERFICIE,OCCUPEE,RESTANT,OCCUPANT,NaN,NaN,NaN
11,6,1,496,496,0,WAFFO KAMGUE FREDDY,D.T,NaN,NaN

In [15]:
def nettoyer_feuille(nom_feuille):
    # 0) NOUVEAU : exclure d'emblée les récaps / totaux / situations
    nom_maj = nom_feuille.upper()
    if any(mot in nom_maj for mot in ["RECAP", "DISPONIBIL", "TOTAL", "SITUATION"]):
        return None

    # 1) Trouver la ligne d'en-tête
    brut = pd.read_excel(chemin, sheet_name=nom_feuille, header=None)
    ligne_entete = None
    for i in range(min(15, len(brut))):
        ligne = brut.iloc[i].astype(str).str.upper()
        if ligne.str.contains("BLOC").any() and ligne.str.contains("LOT").any():
            ligne_entete = i
            break
    if ligne_entete is None:
        return None

    # 2) Relire avec le bon en-tête
    df = pd.read_excel(chemin, sheet_name=nom_feuille, header=ligne_entete)

    # 3) Renommer par mots-clés (CORRIGÉ : SUPERF, RESTANT, OCCUPANT)
    renom = {}
    for col in df.columns:
        c = str(col).upper()
        if "BLOC" in c: renom[col] = "bloc"
        elif "LOT" in c: renom[col] = "lot"
        elif "SUPERF" in c: renom[col] = "superficie"
        elif "RESTANT" in c: renom[col] = "restante"          # capte RESTANT et RESTANTE
        elif "CLIENT" in c or "NOMS" in c or "OCCUPANT" in c: renom[col] = "client"
    df = df.rename(columns=renom)

    # 4) Vérifier les colonnes essentielles
    if not all(c in df.columns for c in ["bloc", "lot", "superficie", "restante"]):
        return None

    # 5) Nettoyage
    df["bloc"] = df["bloc"].ffill()
    for c in ["bloc", "lot", "superficie", "restante"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df.dropna(subset=["bloc", "lot", "superficie"])

    # 6) Statut + cible + TF
    df["statut"] = df["restante"].apply(lambda r: "Vendu" if r == 0 else "Disponible")
    df["vendu"] = (df["statut"] == "Vendu").astype(int)
    df["TF"] = nom_feuille
    if "client" not in df.columns:
        df["client"] = None

    # 7) Colonnes finales
    return df[["TF","bloc","lot","superficie","restante","client","statut","vendu"]].reset_index(drop=True)


# On relance la boucle sur toutes les feuilles
tables, ignorees = [], []
for nom in classeur.sheet_names:
    try:
        resultat = nettoyer_feuille(nom)
        if resultat is not None and len(resultat) > 0:
            tables.append(resultat)
            print(f"OK    {nom:32} -> {len(resultat):3} parcelles")
        else:
            ignorees.append(nom)
    except Exception as e:
        ignorees.append(nom)

print(f"\nFeuilles exploitées : {len(tables)} | ignorées : {len(ignorees)}")

OK    5880                             ->  55 parcelles
OK    5881                             ->  95 parcelles
OK    5262 KADJO                       ->  14 parcelles
OK    KOMGUEM KAINNENG NADEGE          ->   1 parcelles
OK    5792 YANGA                       ->   8 parcelles
OK    6428 LISSOM                      ->  48 parcelles
OK    3638(2)                          ->   9 parcelles
OK    6428(4 et 9)                     ->  15 parcelles
OK    5216 nvo                         ->   6 parcelles
OK    5608                             ->  96 parcelles
OK    5880(02)                         ->  10 parcelles
OK    4192                             ->  26 parcelles
OK    6037                             ->   6 parcelles
OK    3989                             ->  16 parcelles
OK    3368                             ->   4 parcelles

Feuilles exploitées : 15 | ignorées : 22

In [16]:
# Combien de parcelles au total jusqu'ici ?
total = sum(len(t) for t in tables)
print("Total parcelles récupérées :", total)

# Quelles feuilles sont encore ignorées ?
print("\nFeuilles encore ignorées :")
for nom in ignorees:
    print(" -", nom)

Total parcelles récupérées : 409

Feuilles encore ignorées :
 - Feuil1
 - Feuil2
 - Feuil3
 - Feuil5
 - Feuil6
 - 3638
 -  KOMGUEM KAINNENG NADEGE 2
 - RECAP DES DISPONIBILIT
 - Recap des RECAP26
 - DISPONIBILITES
 - Recap 25
 - Dla(Mme PAGUY Epse DJOUMESSI)
 - sup TOTAL DE LIKOUND
 - 3905 nvo
 - 5176 nvo
 - 5066
 - 5608SM
 - TOTAL
 - Situation
 - NGOI EMMANUEL( 29180)
 - ..
 - Feuille37

In [17]:
tf_manques = ["3638", "3905 nvo", "5176 nvo", "5066", "5608SM"]

for nom in tf_manques:
    brut = pd.read_excel(chemin, sheet_name=nom, header=None)
    trouve = False
    # On cherche la ligne qui contient "BLOC" dans les 20 premières
    for i in range(min(20, len(brut))):
        ligne = brut.iloc[i].astype(str).str.upper()
        if ligne.str.contains("BLOC").any():
            colonnes = [str(v) for v in brut.iloc[i].tolist() if str(v) != "nan"]
            print(f"{nom:10} | en-tête ligne {i} : {colonnes}")
            trouve = True
            break
    if not trouve:
        print(f"{nom:10} | aucun 'BLOC' dans les 20 premières lignes")

3638       | en-tête ligne 2 : ['BLOC', 'LOT', 'SUPERFICIE', 'OCCUPEE', 'RESTANT', 'OCCUPANT', 'BLOC', 'SUPERFICIE', 'OCCUPANT']
3905 nvo   | aucun 'BLOC' dans les 20 premières lignes
5176 nvo   | aucun 'BLOC' dans les 20 premières lignes
5066       | en-tête ligne 6 : ['BLOC', 'LOT', 'SUPERFICIE', 'OCCUPEE', 'RESTANT', 'OCCUPANT']
5608SM     | en-tête ligne 2 : ['BLOC', 'LOT', 'SUP( m²)']

In [18]:
# pd.concat empile toutes les tables de la liste, les unes sous les autres
base = pd.concat(tables, ignore_index=True)

print("Base consolidée :", base.shape)
print("Nombre de lotissements (TF) :", base["TF"].nunique())
print("Taux de commercialisation global :", round(base["vendu"].mean()*100, 1), "%")

print("\nRépartition vendu / disponible :")
print(base["statut"].value_counts())

print("\nParcelles par lotissement :")
print(base["TF"].value_counts())

base.head()

Base consolidée : (409, 8)
Nombre de lotissements (TF) : 15
Taux de commercialisation global : 87.5 %

Répartition vendu / disponible :
statut
Vendu         358
Disponible     51
Name: count, dtype: int64

Parcelles par lotissement :
TF
5608                       96
5881                       95
5880                       55
6428 LISSOM                48
4192                       26
3989                       16
6428(4 et 9)               15
5262 KADJO                 14
5880(02)                   10
3638(2)                     9
5792 YANGA                  8
6037                        6
5216 nvo                    6
3368                        4
KOMGUEM KAINNENG NADEGE     1
Name: count, dtype: int64

,TF,bloc,lot,superficie,restante,client,statut,vendu
0,5880,4.0,9.0,500.0,0.0,KAMTE EMMA,Vendu,1
1,5880,4.0,10.0,500.0,0.0,TCHUIMBOU SIKAZI SERGES PATRICK,Vendu,1
2,5880,4.0,11.0,500.0,500.0,ONGUENE CLAUDE BERTRAND JUNIOR,Disponible,0
3,5880,4.0,12.0,500.0,0.0,TCHUIMBOU SIKAZI SERGES PATRICK,Vendu,1
4,5880,4.0,13.0,500.0,500.0,NYOM ANDRE RENE,Disponible,0

In [19]:
# 1) Retirer la feuille parasite (nom de personne, 1 seule parcelle)
base = base[base["TF"] != "KOMGUEM KAINNENG NADEGE"].reset_index(drop=True)

# 2) Vérification finale
print("Base finale :", base.shape)
print("Lotissements :", base["TF"].nunique())
print("Vendu / Disponible :", base["vendu"].sum(), "/", (base["vendu"] == 0).sum())

# 3) Export vers le dossier des données propres
base.to_csv("../02_donnees_propres/base_parcelles.csv", index=False)
base.to_excel("../02_donnees_propres/base_parcelles.xlsx", index=False)

print("\nBase exportée dans 02_donnees_propres/ :")
print(" - base_parcelles.csv")
print(" - base_parcelles.xlsx")

Base finale : (408, 8)
Lotissements : 14
Vendu / Disponible : 358 / 50

Base exportée dans 02_donnees_propres/ :
 - base_parcelles.csv
 - base_parcelles.xlsx